src/Entity/Customer.php
<?php

namespace App\Entity;

use App\Repository\CustomerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CustomerRepository::class)]
class Customer
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    private ?string $surname = null;

    #[ORM\Column(length: 11)]
    private ?string $phone_number = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $address = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $updated_at = null;

    #[ORM\OneToMany(mappedBy: 'customer', targetEntity: ServiceInfo::class)]
    private Collection $serviceInfos;

    public function __construct()
    {
        $this->serviceInfos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): static
    {
        $this->surname = $surname;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): static
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection<int, ServiceInfo>
     */
    public function getServiceInfos(): Collection
    {
        return $this->serviceInfos;
    }

    public function addServiceInfo(ServiceInfo $serviceInfo): static
    {
        if (!$this->serviceInfos->contains($serviceInfo)) {
            $this->serviceInfos->add($serviceInfo);
            $serviceInfo->setCustomer($this);
        }

        return $this;
    }

    public function removeServiceInfo(ServiceInfo $serviceInfo): static
    {
        if ($this->serviceInfos->removeElement($serviceInfo)) {
            // set the owning side to null (unless already changed)
            if ($serviceInfo->getCustomer() === $this) {
                $serviceInfo->setCustomer(null);
            }
        }

        return $this;
    }
}

src/Entity/ServiceInfo.php
<?php

namespace App\Entity;

use App\Repository\ServiceInfoRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ServiceInfoRepository::class)]
class ServiceInfo
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'serviceInfos')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Customer $customer = null;

    #[ORM\Column(length: 255)]
    private ?string $vehicle_brand = null;

    #[ORM\Column(length: 255)]
    private ?string $vehicle_model = null;

    #[ORM\Column(length: 50)]
    private ?string $status = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $vehicle_problem = null;

    #[ORM\Column(length: 50)]
    private ?string $expert = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $repair_date = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $updated_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCustomer(): ?Customer
    {
        return $this->customer;
    }

    public function setCustomer(?Customer $customer): static
    {
        $this->customer = $customer;

        return $this;
    }

    public function getVehicleBrand(): ?string
    {
        return $this->vehicle_brand;
    }

    public function setVehicleBrand(string $vehicle_brand): static
    {
        $this->vehicle_brand = $vehicle_brand;

        return $this;
    }

    public function getVehicleModel(): ?string
    {
        return $this->vehicle_model;
    }

    public function setVehicleModel(string $vehicle_model): static
    {
        $this->vehicle_model = $vehicle_model;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getVehicleProblem(): ?string
    {
        return $this->vehicle_problem;
    }

    public function setVehicleProblem(string $vehicle_problem): static
    {
        $this->vehicle_problem = $vehicle_problem;

        return $this;
    }

    public function getExpert(): ?string
    {
        return $this->expert;
    }

    public function setExpert(string $expert): static
    {
        $this->expert = $expert;

        return $this;
    }

    public function getRepairDate(): ?\DateTimeInterface
    {
        return $this->repair_date;
    }

    public function setRepairDate(\DateTimeInterface $repair_date): static
    {
        $this->repair_date = $repair_date;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Controller/DashboardController.php
<?php

namespace App\Controller;

use App\Repository\CustomerRepository;
use App\Repository\ServiceInfoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[IsGranted('ROLE_USER')]
class DashboardController extends AbstractController
{
    #[Route('/dashboard', name: 'app_dashboard')]
    public function index(ServiceInfoRepository $serviceInfoRepository,CustomerRepository $customerRepository): Response
    {
//        if (!$this->isGranted('ROLE_USER')){
//            throw $this->createAccessDeniedException('No access for you');
//        }

        $serviceInfos = $serviceInfoRepository->getServiceInfo();
        $totalCustomer = $customerRepository->getTotalCustomer()[0]['count'];
        $totalVehicle = $serviceInfoRepository->getTotalVehicles()[0]['count'];

        return $this->render('dashboard/dashboard.html.twig', [
            'controller_name' => 'DashboardController',
            'servicesInfos'=>$serviceInfos,
            'totalCustomer'=>$totalCustomer,
            'totalVehicle'=>$totalVehicle
        ]);
    }
}

templates/dashboard/dashboard.html.twig
{% extends 'base.html.twig' %}

{% block title %}Car Repair Tracking{% endblock %}

{% block menuTitle %}Dashboard{% endblock %}

{% block content %}
    <div class="container-fluid px-4">
        <div class="row g-3 my-2 d-flex justify-content-around align-items-center">
            <div class="col-md-4">
                <div class="p-3 bg-white shadow-sm d-flex justify-content-around align-items-center rounded">
                    <div>
                        <h3 class="fs-2">{{ totalVehicle }}</h3>
                        <p class="fs-5">Total Vehicles</p>
                    </div>
                    <i class="fas fa-car fs-1 primary-text border rounded-full secondary-bg p-3"></i>
                </div>
            </div>

            <div class="col-md-4">
                <div class="p-3 bg-white shadow-sm d-flex justify-content-around align-items-center rounded">
                    <div>
                        <h3 class="fs-2">{{ totalCustomer }}</h3>
                        <p class="fs-5">Total Customers</p>
                    </div>
                    <i class="fa-solid fa-users fs-1 primary-text border rounded-full secondary-bg p-3"></i>
                </div>
            </div>
        </div>

        <div class="row my-5">
            <h3 class="fs-4 mb-3">Recent Repair</h3>
            <div class="col">
                <table id="example" class="table table-striped" style="width:100%">
                    <thead>
                    <tr>
                        <th scope="col" width="50">ID</th>
                        <th scope="col">Customer First Name</th>
                        <th scope="col">Customer Last Name</th>
                        <th scope="col">Customer Phone</th>
                        <th scope="col">Vehicle Brand</th>
                        <th scope="col">Vehicle Model</th>
                        <th scope="col">Expert of</th>
                        <th scope="col">Status</th>
                        <th scope="col">Vehicle Problem</th>
                        <th scope="col">Repair Date</th>
                        <th scope="col">Updated Date</th>
                        {% if is_granted("ROLE_ADMIN") %}
                        <th scope="col">Edit</th>
                        <th scope="col">Delete</th>
                        {% endif %}
                    </tr>
                    </thead>
                    <tbody>
                    {% for servicesInfo in servicesInfos %}
                        <tr>
                            <th scope="row">{{ servicesInfo.id }}</th>
                            <td>{{ servicesInfo.getCustomer.firstname }}</td>
                            <td>{{ servicesInfo.getCustomer.surname }}</td>
                            <td>{{ servicesInfo.getCustomer.phoneNumber }}</td>
                            <td>{{ servicesInfo.vehicleBrand }}</td>
                            <td>{{ servicesInfo.vehicleModel }}</td>
                            <td>{{ servicesInfo.expert }}</td>
                            <td>{{ servicesInfo.status }}</td>
                            <td>{{ servicesInfo.vehicleProblem }}</td>
                            <td>{{ servicesInfo.repairDate | date ('d M Y') }}</td>
                            <td>{{ servicesInfo.updatedAt | date ('d M Y') }}</td>
                            {% if is_granted("ROLE_ADMIN") %}
                            <td><a href="#" class="btn btn-primary"><span><i class="fa fa-pencil" aria-hidden="true"></i></span></a></td>
                            <td><a href="#" class="btn btn-danger"><span><i class="fa fa-trash" aria-hidden="true"></i></span></a></td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}